"""Frozen configuration, data materialization, and provenance for the SI rebuttal."""

from .config import (
    FIXED_COUNTS,
    FIXED_DATASETS,
    FIXED_MODELS,
    FIXED_RUNTIME,
    FIXED_SEED_NAMESPACE,
    FIXED_STATISTICS,
    FIXED_VALIDATION,
    ConfigError,
    ResolvedConfig,
    SweepConfig,
    load_base_config,
    load_sweep_config,
)
from .data import (
    DataMaterializationError,
    DocumentRecord,
    ImmutableHFDatasetLoader,
    LoadedDatasetRows,
    MaterializedDomain,
    SelectedChunk,
    build_code_documents,
    build_wikipedia_documents,
    materialize_domain,
    materialize_frozen_domain,
)
from .provenance import (
    ProvenanceError,
    atomic_write_json,
    canonical_json_bytes,
    compact_json_seed,
    sha256_tree,
)

__all__ = [
    "FIXED_COUNTS",
    "FIXED_DATASETS",
    "FIXED_MODELS",
    "FIXED_RUNTIME",
    "FIXED_SEED_NAMESPACE",
    "FIXED_STATISTICS",
    "FIXED_VALIDATION",
    "ConfigError",
    "DataMaterializationError",
    "DocumentRecord",
    "ImmutableHFDatasetLoader",
    "LoadedDatasetRows",
    "MaterializedDomain",
    "ProvenanceError",
    "ResolvedConfig",
    "SelectedChunk",
    "SweepConfig",
    "atomic_write_json",
    "build_code_documents",
    "build_wikipedia_documents",
    "canonical_json_bytes",
    "compact_json_seed",
    "load_base_config",
    "load_sweep_config",
    "materialize_domain",
    "materialize_frozen_domain",
    "sha256_tree",
]
